services:
  backend:
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: build
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:5173"
