"""initial migration

Revision ID: 00f2f85bc04a
Revises: 
Create Date: 2026-04-24 19:07:44.433523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00f2f85bc04a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_scheduled_time'), 'medication_schedules', ['scheduled_time'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_reference_date'), 'medication_logs', ['reference_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_logs_reference_date'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medication_schedules_scheduled_time'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
