"""update notification schema and constraints

Revision ID: 1592115f871e
Revises: 89f08bdb9807
Create Date: 2026-05-06 15:20:47.857805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1592115f871e'
down_revision: Union[str, Sequence[str], None] = '89f08bdb9807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ix_unique_notification_per_day'), 'notifications', type_='unique')
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_unique_constraint('ix_unique_notification_per_day_type', 'notifications', ['scheduled_id', 'reference_date', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_unique_notification_per_day_type', 'notifications', type_='unique')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.create_unique_constraint(op.f('ix_unique_notification_per_day'), 'notifications', ['scheduled_id', 'reference_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
