"""add_end_date_to_schedule

Revision ID: 6588b8813d0d
Revises: 86176fa5717b
Create Date: 2026-07-09 17:05:14.795836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6588b8813d0d'
down_revision: Union[str, Sequence[str], None] = '86176fa5717b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_schedules', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_schedules', 'end_date')
    # ### end Alembic commands ###
