"""
removing uniq on notification madication_schedule.id

Revision ID: 86176fa5717b
Revises: 1592115f871e
Create Date: 2026-05-07 22:52:19.501034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86176fa5717b'
down_revision: Union[str, Sequence[str], None] = '1592115f871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ix_unique_notification_per_day_type'), 'notifications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('ix_unique_notification_per_day_type'), 'notifications', ['scheduled_id', 'reference_date', 'type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
