"""add recurrence fields

Revision ID: 89f08bdb9807
Revises: 40fe526f6de6
Create Date: 2026-05-03 22:48:08.926389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89f08bdb9807'
down_revision: Union[str, Sequence[str], None] = '40fe526f6de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_schedules', sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('medication_schedules', sa.Column('interval', sa.Integer(), nullable=False))
    op.add_column('medication_schedules', sa.Column('days_of_week', sa.JSON(), nullable=True))
    op.add_column('medication_schedules', sa.Column('day_of_month', sa.Integer(), nullable=True))
    op.add_column('medication_schedules', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_schedules', 'start_date')
    op.drop_column('medication_schedules', 'day_of_month')
    op.drop_column('medication_schedules', 'days_of_week')
    op.drop_column('medication_schedules', 'interval')
    op.drop_column('medication_schedules', 'frequency')
    # ### end Alembic commands ###
